name: flutter_neumorphic_plus_fork

description: A forked copy of a ready to use, Neumorphic ui kit for Flutter.
    Dark theming compatible & fully customizable.

version: 3.3.1

publish_to: none

homepage: https://github.com/KDCinfo/Flutter-Neumorphic-Plus-Fork

environment:
  sdk: ^3.0.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: NeumorphicIcons
      fonts:
        - asset: fonts/NeumorphicIcons.ttf
